### ISSUE TITLE
rapidgator.net

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#166]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   rapidgator.net
   www.rapidgator.net

**Comment by xxcriticxx** [comment]
@funilrys dis you missed this or you choose not to add?

**Comment by funilrys** [comment]
@xxcriticxx No, I did not miss this one. 

It's blocked by lists with big reputation than this repository, like for example the one maintained by Steven Black.

So I do not see why I should whitelist it.

**Comment by xxcriticxx** [comment]
you whitelisted `openload.co` which is same as `rapidgator.net` just another file locker

**Comment by funilrys** [comment]
@xxcriticxx `openload.co` is not blocked by other lists with a big reputations :+1:

**Comment by xxcriticxx** [comment]
no problem thanks for you answer

**Comment by elico** [comment]
@funilrys Steven Black might be a well respected and have a good reputation and I don't doub't it but I have seen that due to GeoIP rules some sites looks a bit different from couple places on the globe and there for some rules in a specific location might not be right for another.

**Comment by funilrys** [comment]
Good point @elico and I know it. Checking if it's part of StevenBlack list and/or other big lists which are updated almost every day is just one thing between other I take into consideration. One of the other consideration I take is also, for example: I take the time to test the accessibility for many countries including mine which can forces website like #182 to be down or inaccessible in my country.

That's why if you use @pi-hole like @xxcriticxx you have the ability to whitelist yourself. 

Also, I'm working on the next script review so that nobody can generate :+1: 

Thanks for pointing out @elico and have a nice day/night.

**Comment by elico** [comment]
@funilrys I didn't understood this:

> Also, I'm working on the next script review so that nobody can generate 👍

next script? what script review?
@pi-hole looks pretty nice here: https://www.youtube.com/watch?v=J6_3RH4DK1A
I have seen [DNSthingy](https://dnsthingy.com/) since it's birth and depends on the tools you have you can choose your black and white listing methods.
Hosts file is good but if it's being queried I believe that a similar DNS service will provide the same effect more efficiently.
IE in a DNS service you can apply an "ALL .ubuntu.com" blacklist rule or the opposite which will depend on your policy DENY,ALLOW or ALLOW,DENY. 
I already have the DNS server service a DB and all the coding but missing a nice WEBUI or cli tool like @pi-hole
