### ISSUE TITLE
vpn

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#269]
what's your thoughts on vpn? 

this list is blocking every possible service in the world

**Comment by elico** [comment]
@xxcriticxx from what I know about the VPN world there is one big scam within it.
It's much easier to lure a user into a VPN and catch him hands on compared to raw IP based enforcement.
If you really need an IP which is not local use some kind of VPS, it costs less then a VPN service as far as I know(even a 128 MB linux can do the trick).

**Comment by xxcriticxx** [comment]
@elico but VPS only has one ip right? in my case i need European ip thats why i use VPN's

**Comment by elico** [comment]
@xxcriticxx you are right but it's only If you trust the VPN provider then it should be white-listed for you.
In general VPN or proxy providers are not always legal.
In many countries they must have an ISP license which they lack and it's an issue a big one.

If you don't know and have not seen I have, there are many VPN providers which snoop your traffic and use it.
What would you do if they snoop your cookies, dns and other sensitive details?

**Comment by xxcriticxx** [comment]
Majority of my traffic is streaming video 

Vps has its limits plus it also logs traffic 

We can continue this argument for days :)

**Comment by elico** [comment]
@xxcriticxx it's not an argument.
You have your side and requirements and others have their.
I do not have any objection with categorizing urls and domains like many filtering providers do.
What do you say about opening a VPN providers domains list?

**Comment by mitchellkrogza** [comment]
@elico @xxcriticxx @funilrys might be a good idea to have a list of VPN providers people could use that to whitelist VPN providers. 🤔

**Comment by xxcriticxx** [comment]
@mitchellkrogza should we do same for porn? some people like @funilrys use lots porn ;)

**Comment by funilrys** [comment]
It might be a good idea indeed for the VPN @mitchellkrogza.

For the porn part, let me first say that having a GF is way better than that (No I do not intend to marry my computer like the biggest programmer stereotype). But I'm pretty sure you were talking about young people or student in general @xxcriticxx which, may also be another stereotype depending of the country, the education or even the religion.

Otherwise, the next step will be to help people having their own list by distributing a script which can whitelist a given list of domains. That will give us the opportunity to create a list of domains do whitelist.

That will be done (asap) under the [dev-center](https://github.com/Ultimate-Hosts-Blacklist/dev-center).

Cheers,
Nissar.

**Comment by xxcriticxx** [comment]
@elico good joke!

**Comment by funilrys** [comment]
Closing. Please report to Ultimate-Hosts-Blacklist/dev-center#1
