### ISSUE TITLE
The right way to verify that there was a change in the list version.

### ISSUE THREAD

**Issue by elico** [mitchellkrogza/Ultimate.Hosts.Blacklist#278]
Currently I have seen that the only place I can see the version of the blacklist is at:
- https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/raw/master/README.md

under:

```- Version: **V1.1123.2018.04.15**```

which is between line 10 to 20 of the file.

**can I count on it to always be there as it is?**
IE I want to write a bash script that will check for a version change at github every 8 hours and will trigger an update download\fetch from github.

If not or if possible to have some "version.txt" file that will contain the current version with some etag or md5\sha1\sha256 hash that will help to verify that the downloaded file is indeed the one that I should receive.

**Comment by mitchellkrogza** [comment]
@elico yesy indeed, once that Readme is updated with a new version number then the RAW links are also updated too, that you can count on. We only update Ultimate once a day using Cron so you instead of every 8 hours you can safely schedule it for 14h00 UTC once a day

**Comment by elico** [comment]
@mitchellkrogza Thanks!
Will write this one.

**Comment by mitchellkrogza** [comment]
Great @elico keep us posted.

**Comment by elico** [comment]
@mitchellkrogza the basic script I cam up with is:
- http://gogs.ngtech.co.il/elicro/ultimate-hosts-bl-utils/raw/master/update-scripts/download-latest.sh

I have couple other tools that will come later.

**Comment by funilrys** [comment]
Just a little comment about your code @elico. 

Please avoid UPPERCASE variable as it can be confusing for people who want to start learning by reading your code (yes that exist).
Indeed UPPERCASE are generally reserved for the systemwide/environment variables like  `${PATH}`, `${HOME}` or even `${EDITOR}`.

------------------------------

You use `${VERSIONFILE}` only once, so you do not need a variable for that. Simply append it to the URL.

------------------------------

I'm not a big fan of oneliner line @mitchellkrogza but you may find the following as an alternative to `CURRENTVERSION=$(curl "$GITROOT$VERSIONFILE" 2>/dev/null |grep "Version: \*\*" |gawk '{print $3}')`

```
$ CURRENTVERSION=$(curl "$GITROOT$VERSIONFILE" 2>/dev/null | grep -E "Version" | cut-d ' ' -f3
```

------------------------------

Please also consider using the format `${variableName}` when calling variable as it's cleaner than `$variableName`. 

You may also learn later (if it's not already the case) that you can to get a substring of a string which can be made with `${variableName:1:5}` which is only possible with that format. 

So keep it clean, understandable and safe and the world will be a better place for the learner :wink:.

------------------------------

# Question

* Why are you exporting variable (for example `export LISTSJAIL` when you directly use then like the following? 

```
echo ${thisIsMyAwesomeVariable}
```

------------------------------
# Post scriptum

I'm only a student and my only experience in Bash/Shell in open source project is [funceble](https://github.com/funilrys/funceble) along with other really older projects. 

This is just pieces of advice do not take them personally. 

For me, it's important that when you publish code in public that it should be clear because not only experienced programmer may take a look at it. 

If those pieces of advice were present when I started to read and learn code, I would not waste so much time trying to find the right way. 

Anyway, feel free to follow or not those (little) pieces of advice.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys  i just read this....your advice is right on the spot....i am a **learner**(bellow beginner) and i know exactly what you mean.You should see my little scripts that i made to update my hosts files....
.....all oneliners hehehehe
