### ISSUE TITLE
bbc.co.uk

### ISSUE THREAD

**Issue by JamesKingdom** [mitchellkrogza/Ultimate.Hosts.Blacklist#321]
It seems http://bbc.co.uk is blocked, is this on purpose?

**Comment by funilrys** [comment]
Hello @JamesKingdom and welcome here!

I just checked into our system and yes it is because it always redirects to `www.bbc.com`.

We choose to not accept redirections into our whitelist list because they are easy to change and uncontrollable.

Have a nice day/night. 
Cheers,
Nissar
_______________

Closing. But feel free to continue the discussion.
