### ISSUE TITLE
 tmblr.co

### ISSUE THREAD

**Issue by xxcriticxx** [mitchellkrogza/Ultimate.Hosts.Blacklist#362]
Match found in list.34.hosts.ubuntu101.co.za.domains:
   tmblr.co

**Comment by funilrys** [comment]
It redirects to `tumblr.com`

___________
Closing.

**Comment by xxcriticxx** [comment]
@funilrys i know it redirects so why block it?

**Comment by funilrys** [comment]
Because we agreed not to whitelist redirection. 

For example tomorrow we have an angry employee who changes the redirection to a malware...
Another example if tomorrow the domain is not renewed somebody else can buy it and turn it into a Phishing or malware distributor ... 

I'll let @mitchellkrogza complete my anwer if it's not complete...
