### ISSUE TITLE
file is too big, blocks isp, dns client, cant be renamed or deleted

### ISSUE THREAD

**Issue by zoulztealer** [mitchellkrogza/Ultimate.Hosts.Blacklist#517]
well, thanks for the gathering of all the bad hosts, but actually this file is not applicable. as soon as i installed it (windows 10 education 1903) it froze my ic and i could not remove or rename the file anymore, because it was blocked / in use by the dns client. had to reboot to safe mode to get rid of it again. perfect example of a host file that has become "too good".

**Comment by funilrys** [comment]
Hi @zoulztealer,

sorry to hear about that. Do you have any idea about how we can improve in the future? I'm interested to hear about any inputs.

My idea is to provide in near the future a way of allowing people to get their own "custom" list based on all data we have into [our backend](https://github.com/Ultimate-Hosts-Blacklist). 

Is that a possible solution for Windows 10 users?

Thanks for your feedback.

Cheers,
Nissar

**Comment by dnmTX** [comment]
@funilrys  one solution is to compress it(at least 6 domains per line),but still,such a large lists,i'm not sure that it'll help much.

> My idea is to provide in near the future a way of allowing people to get their own "custom" list based on all data we have into our backend.

This is probably the best there is,not only for Windows users but for everyone.

**Comment by zoulztealer** [comment]
maybe a seperate app could manage and incooperate the file effectively. the windows framework alone will probably not be suitable for this.

**Comment by spirillen** [comment]
A little hack for @zoulztealer as you are degraded to windows i suggest you installs the [Unbound](https://nlnetlabs.nl/projects/unbound/download/) which maintain a windows version of there DNS server, very small, fast and nimble :) 

Make a small script that rewrites the hosts file into a rpz.db file (text file (UTF-8))

what you have to do it converting
```
[127.0.0.1|0.0.0.0] some-fucked-up.tld
```
Into
```
local-zone: "facebook.com" always_nxdomain
local-zone: "google.com" always_nxdomain
local-zone: "gstatic.com" always_nxdomain
local-zone: "improving.duckduckgo.com" always_nxdomain
local-zone: "googlesyndication.com" always_nxdomain
local-zone: "google-analytics.com" always_nxdomain
local-zone: "googleapis.com" always_nxdomain
local-zone: "googledomains.com" always_nxdomain
local-zone: "doubleclick.net" always_nxdomain
local-zone: "microsoft.com" always_nxdomain
```

Now you have a very fast self hosted recursor that queries the root servers it self, no DNS tracking by your school or ISP... COOL

PS: Remember to change your network setup to use you freshly install DNS server on `127.0.0.1/::1`

**Comment by zoulztealer** [comment]
@spirillen you know i have to use windows for gaming because linux is not good enough yet. ive been trying it since 11 years now lol and waiting on it to get better, but see even valve has a hard time at making a os for gaming out of it. its not bad and runs great in parts, tbh i love linux actually, but its just not where it has to be yet. btw i get your tip, but id rather use vpn or tails then if needed. on windows id just change my dns server of the tcp ip v4 / v6 protocol to have similar effect and easy to do. still not sure if the big file still would not freeze the app or windows. cheers ;)

**Comment by spirillen** [comment]
> or gaming because linux is not good enough yet

Shhh, don't tell my well playing games on linux that :wink: 

But a little update to the previously post.

It turns out that @scripttiger already do the RPZ conversion from Steven Blacks lists https://scripttiger.github.io/alts/ which increase the import that way around... Just a cent of info :) 

:beers:

**Comment by zoulztealer** [comment]
so i take the file from script tiger and can import it into unbound? stuff like dota2 runs great on linux. i wish id would run all games that run on win though. :'(

**Comment by spirillen** [comment]
@zoulztealer yes to all :)  

My little sister who is running on a win10 home have the Unbound installed with the RPZ running (100/100mb fiber) and her peers times have gone down on WOW, also because I have set it up to block 20% of her DNS queries to Nvidia tracking etc. 

So yes, the results with 
```python
        prefetch: yes
        prefetch-key: yes

        qname-minimisation: yes
        cache-min-ttl: 3600
        infra-cache-numhosts: 1000000
```

Have lowered her DNS query time via `google` DNS to about the half with her own unbound.

For a note: The reason I suggest the unbound on windows, is that most of the users here might be running on a Home edition rather than a pro edition, and that Unbound is the only really fast and reliable third party DNS server I have found that can be installed on a home edition. (Feel very free to update this knowledge)

You can havest a starter config to unbound on windows home [here](https://gitlab.com/rpz-zones/toolbox/blob/master/unbound/windows%20configs/service.conf) and here for [man unbound](https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/) (Configuration of unbound)

**Comment by zoulztealer** [comment]
thanks looks really nice. there is a lot of tracking / telemtry with gaming. ive killed nvidia telemtry service, tasks etc with autoruns. not sure if you heard of this: https://www.guru3d.com/files-details/nvidia-driver-slimming-utility.html ive installed unbound and can already tell a difference at site access, i believe, like much faster. it runs as a service with a config, right? tweaking it right now.

**Comment by spirillen** [comment]
Seems right, but a few tweaks could help.

from above you see this
```python
# Will make sure the previously cached
# Queries is always fresh, and by that keep
# DNS Query times at 0msec
prefetch: yes

# Rather optional, but actually nice on very slow
# ADSL connection
prefetch-key: yes

# Optimize your privacy
qname-minimisation: yes

# To raise the cache time for non RFC standard TTL.
# This is from most CDN with TTl @ 30sec , and on daily
# basic useless. Here rewrite TTl to 1 hour 
cache-min-ttl: 3600

# To leave room for cashing all "always_nxdomain"
infra-cache-numhosts: 1000000
```

Second to this you should lower the number of threads to something like 2-4 as 16 is server sized to 1 mill queries a second

Third, Congratulation, you now have a fully functional DNS recursor on your home network that can help protect all of your devices... change your DNS in your DHCP server (properly router)

Fouth: when configuring you like to set `verbose: 2` and enable logging, and when you happy disable both :)

**Comment by ScriptTiger** [comment]
@zoulztealer, I'm with you on the Windows gaming versus Linux. Games released for Xbox (named for DirectX Box) and Windows are obviously optimized for DirectX, which Linux tries to emulate but simply can't efficiently because all the libraries, etc., are all proprietary and closed source and they can only make guesses about how it actually works internally. OpenGL is supposed to have many improvements over DirectX, but those games simply are not optimized for it since they were designed with DirectX in mind from the ground up.

This isn't a statement of whether DirectX is better or worse than OpenGL, it's just the fact that game developers developing for Xbox and Windows releases optimize their games for DirectX. Why? Well, because obviously Xbox only runs DirectX, hence the name DirectX Box, so they're not going to waste money optimizing for OpenGL on top of that since it's not the majority of users and game developing is damn expensive and resource intensive from the get-go and optimizing for two APIs at the same time just doesn't work out economically.

Linux gamers can boast all day long about how much faster gaming is on Linux versus Windows, but it really depends on the game and how it was designed. Yes, it's true that games optimized for OpenGL running on a streamlined Linux box geared towards gaming will run faster than it ever could on a Windows system. But when you throw in games that you have to emulate DirectX with on Linux because the experience gets jacked up using OpenGL because it wasn't written with that API in mind, your performance and overall experience seriously suffers and this is an undeniable fact.

**Comment by spirillen** [comment]
@ScriptTiger your right have sad it ever is...

But i still awaiting the day where games starts getting developed for *nix over Microsoft... I'll bet Microsoft would loos a lot of terrain as they would have like 1% harvested(stolen) privacy data to offer there customers

That day, I'll get back into the industry :man_office_worker:

**Comment by zoulztealer** [comment]
%)
