### ISSUE TITLE
Unable to connect to internet after changing hosts file.

### ISSUE THREAD

**Issue by hprincivil** [mitchellkrogza/Ultimate.Hosts.Blacklist#533]
As soon as I run the install batch file on my Windows 10 machine I lose complete connectivity to the internet.

**Comment by NoFuchsGavin** [comment]
Exactly same issue here

**Comment by mitchellkrogza** [comment]
The hosts file is just too big for Windows to consume, we don't see this limitation on linux machines. Our DNS service will be the only way forward which hopefully will be back up and running in early 2020.

**Comment by spirillen** [comment]
AAahhh not entirely true

> we don't see this limitation on linux machines

But yes the limit is way higher, but i have killed a HP ML350G6 with raid5 SCSI 10.000RPM 192GB Ram with a /ets/hosts file :+1:

**Comment by Rikj000** [comment]
Yea indeed. I completely lost internet connectivity on my Windows 10 machine.

Also wasn't able to run the uninstaller script successfully or replace the hosts file manually with administrator rights since it was constantly in use by the svchost.exe process.

I was able to restore my hosts file when booting in safe mode without internet connectivity tho 😄

**Comment by spirillen** [comment]
Hi @Rikj000 may I suggest you try with unbound for windows? 

Here is a little why: https://github.com/StevenBlack/hosts/issues/1057

**Comment by AnonymousPoster** [comment]
There is actually already some privacy enhanced DNS-severs up...

https://www.mypdns.org/wiki#DNSServers

Please report any "errors" at https://github.com/mypdns/matrix/issues

**Comment by funilrys** [comment]
Hello there, I'm closing this. The issue with windows is known and it may get better with the time as @microsoft give the impression that they want to make really change to show how much it "❤️ Linux".

In the meantime, I reopened: #293 .
It will take a bit of time until we get a second IP but if it is not a problem (I don't use Windows on daily basic) then send me a message and I will give you the IP so that you can test it (Same for other who want to test it!).

Stay safe and healthy!
Nissar

**Comment by spirillen** [comment]
> `@microsoft` give the impression that they want to make really change to show how much it ":heart: Linux".

:rofl: 

> It will take a bit of time until we get a second IP

Have you considered setting up a VPS at hetzner.de? I use four of them to my DNS setup

**Comment by xbbdc** [comment]
For those on Windows using the hosts file, have you tried turning off DNS Client service?
https://tinyapps.org/blog/201809300700_large_hosts_file.html

**Comment by spirillen** [comment]
It's the same as what @ScriptTiger is dealing with in one of his projects, but he have a --compress lvl switch to add up to  9 hosts per line 

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/23

**Comment by friends96** [comment]
> For those on Windows using the hosts file, have you tried turning off DNS Client service?
> 
> https://tinyapps.org/blog/201809300700_large_hosts_file.html
> 
> > **[Large hosts file causes networking issues in Windows 10](https://tinyapps.org/blog/201809300700_large_hosts_file.html)**

For anyone troubleshooting the big hosts file problem. It is not very straightfoward to turn off DNS Client service. At least so it was for me. This video helped me a lot https://www.youtube.com/watch?v=6HrCqcKF5CY
in Written summary: from search bar open "Registry Editor", browse to Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache
![image](https://user-images.githubusercontent.com/30908380/89486450-77d9d280-d779-11ea-88d4-8be188d383e0.png)
select the Registry that says "Start" and change that 2 to a 4
Then reboot and you can modify the hosts file
