### ISSUE TITLE
Apple blocked?

### ISSUE THREAD

**Issue by alexwasserman** [mitchellkrogza/Ultimate.Hosts.Blacklist#535]
domains0.list has apple.com in it - so, whoever sourced that, I'd like to tag for Awards and Shame.

**Comment by alexwasserman** [comment]
I'm an idiot and sourced the wrong domains file.

**Comment by alexwasserman** [comment]
$ curl https://hosts.ubuntu101.co.za/domains.list 2>/dev/null | grep '^apple.com$'
apple.com
$ curl https://hosts.ubuntu101.co.za/domains.list 2>/dev/null | grep 'githubusercontent.com'
gist.githubusercontent.com
www.gist.githubusercontent.com

**Comment by dnmTX** [comment]
@alexwasserman  `apple.com` is not blocked by the Ultimate.Hosts.Blacklist so look for the problem elsewhere please.

**Comment by alexwasserman** [comment]
curl -s https://hosts.ubuntu101.co.za/hosts | grep '0.0.0.0 apple.com$'

**Comment by dnmTX** [comment]
@alexwasserman apologies,should've check the hosts file first.Stand by please.....

@funilrys ,the [search](https://hosts.ubuntu101.co.za/app/contents/) didn't find it,also searched few others domains with `apple` word in them and nothing showed up. Not sure what's going on but the domain is indeed in the [hosts file](https://hosts.ubuntu101.co.za/hosts).
As it is easier for me to whitelisted and be done with it will wait for your confirmation due to search results showed nothing so i'll assume for now that the Linux hosts file hasn't been updated since we removed those complicated lists. Please inspect and let me know what's next. Thanks.

**Comment by alexwasserman** [comment]
@dnmTX - no probs.

Also, noticed that gist.githubusercontent.com in there too.

That’s a pretty popular domain (ironically part of github, given we’re on here now).

Probably want to whitelist both.

**Comment by dnmTX** [comment]
@alexwasserman  will do,if it comes to this.Let's first wait for @funilrys to check everything and will go from there.

**Comment by funilrys** [comment]
Hello there, happy new year!

Sorry for the delay.

@dnmTX, I had to fix some sync issues on the server. It's now fixed.

@dnmTX [:eyes:](https://hosts.ubuntu101.co.za/app/api/contents/lookup/all-list?query=apple.com) (this is a link :wink:)

```json
[
    {
        "description": "Test of https://www.dshield.org/feeds/suspiciousdomains_Low.txt",
        "filename": "clean.list",
        "name": "DShield.org-Suspicious-Domain-List",
        "slug": "Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List",
        "subject": "apple.com"
    },
    {
        "description": "Test of https://www.dshield.org/feeds/suspiciousdomains_Low.txt",
        "filename": "volatile.list",
        "name": "DShield.org-Suspicious-Domain-List",
        "slug": "Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List",
        "subject": "apple.com"
    },
    {
        "description": "Test of https://www.dshield.org/feeds/suspiciousdomains_Low.txt",
        "filename": "whitelisted.list",
        "name": "DShield.org-Suspicious-Domain-List",
        "slug": "Ultimate-Hosts-Blacklist/DShield.org-Suspicious-Domain-List",
        "subject": "apple.com"
    }
]
```

So now, It's was removed from upstream but it's still in our infrastructure because it's still testing right now. As we loosed for 2 days. I think we can whitelist this on our end @dnmTX. Feel free to take action.

Note: as it has almost 100,000 entries, it will take some time to test the whole list. So whitelisting is probably better so that in the generation of tomorrow it will be removed.


Thanks for the feedback @alexwasserman and sorry for the inconvenience and delay from my side. We are working on it.

Cheers!
