### ISSUE TITLE
Pornhub breaking

### ISSUE THREAD

**Issue by p1r473** [mitchellkrogza/Ultimate.Hosts.Blacklist#539]
My issue was closed in #532 however I believe this is still an issue (I was not able to re-open the issue)
Please remove ci.phncdn.com and di.phncdn.com from the blocklist.
With these 2 domains blocked, Pornhub looks like this:
![image](https://user-images.githubusercontent.com/9235633/75072926-71ef7e00-54c6-11ea-8139-ca36e0b95c9e.png)

**Comment by p1r473** [comment]
Trying to validate...

**Comment by p1r473** [comment]
@funilrys I am having a really hard time validating which domains are breaking Pornhub
It is one of:
ci.phncdn.com
di.phncdn.com
cm.phncdn.com
ew.phncdn.com
cdn1-smallimg.phncdn.com
cdn1d-static-shared.phncdn.com
cs.phncdn.com

**Comment by dnmTX** [comment]
Ok,i admit i was wrong on the first issue due to on my end those two domains are not dns blocked but my adblocker is blocking some nasty scripts from them.
Sooo...this is the case here...**PING @smed79** as the lists owner.
@funilrys you included one of the **EXTRA** @smed79's [lists](https://github.com/Ultimate-Hosts-Blacklist/smed79_blacklist_nsfw) which i believe is more for individual use and not for everyone due to probably most of the domains are breaking something.If this is the case it'll be probably for the best if that list is removed from the Ultimate-Hosts...but let's wait for verification first and i guess it's up to you two to decide the next step.
@p1r473  apologies again,the issue is on track to be fixed soon 👍

**Comment by funilrys** [comment]
Let's continue this in the backend (for history purpose)!

**Comment by p1r473** [comment]
All good now, thanks!
